### ISSUE TITLE
A problem with identification and estimate function

### ISSUE THREAD

**Issue by mfaragd** [donotdespair/bsvars#28]
Dear Tomasz Woźniak,
Thank you very much for the interesting package!

I have two problems while using the package to estimate the SVAR model. 
**First, the burn-in step does not work when I identify the matrix B:**
```
> library(bsvars)
> set.seed(123)
> # upload data
> data(us_fiscal_lsuw)
> ##########################################################
> #Specify the identification scheme:
> #nonrecursive:
> B = matrix(c(T,T,T,F,F,T,F,T,T),3,3);B
     [,1]  [,2]  [,3]
[1,] TRUE FALSE FALSE
[2,] TRUE FALSE  TRUE
[3,] TRUE  TRUE  TRUE
> #########################################################
> #bayesian var with stochastic volatility errors
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> # run the burn-in
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
```

**Second, the function "estimate_bsvar_sv" does not work:**
```
> burn_in        = estimate_bsvar_sv(specification, 3, thin = 2)
Error in estimate_bsvar_sv(specification, 3, thin = 2) : 
  could not find function "estimate_bsvar_sv"
```

Please note that this is my package version
> packageVersion("bsvars")
[1] ‘1.0.1.9000’

I am looking forward to hearing from you.

**Comment by mfaragd** [comment]
Dear Tomasz Woźniak,

I would like to remind you of my below issue with the package. Could you please help with this?

I am looking forward to hearing from you.

**Comment by donotdespair** [comment]
Hi Dear @mfaragd 

Thank you for your issue and your interest in this package. 

Let me first address your second point. Version 1.0.1.9000 of the package is the developer version. It is a preparation for the package version 2.0.0 that I am planning to release within a month or two. This version will not be backward-compatible. One of the features in the new version is that all the functions `estimate_bsvar*`, such as yours `estimate_bsvar_sv` from version 1.0.0 of the package, will be discontinued and replaced by one method/function `estimate`. Provided the specification object of a certain type, this function will automatically apply the right estimation algorithm. You have already used it in your first example.

Please, follow the examples from version 1.0.1.9000 for the sample application of the function `estimate`.

I hope that this is helpful.

Greetings,

Tomasz

**Comment by donotdespair** [comment]
Hi @mfaragd 

Regarding the first point. The error message means that some of the matrix inversions cannot be performed. The package is quite robust in this respect as it implements elements of defensive coding. Still, not al the cases can really be covered.

May I suggest running the code with a different input to `set.seed()`? In many cases, only this change makes the algo run well. Please, let me know if this does not solve the issue. I will look at it more closely.

Greetings,

Tomasz

**Comment by mfaragd** [comment]
Hi @donotdespair 

I have tried different inputs in set.seed(), but I still have the same issue. Could you please help with this?



Here is the output:


```
> B = matrix(c(T,T,T,F,F,T,F,T,T),3,3);B
     [,1]  [,2]  [,3]
[1,] TRUE FALSE FALSE
[2,] TRUE FALSE  TRUE
[3,] TRUE  TRUE  TRUE
> library(bsvars)
> set.seed(1)
> data(us_fiscal_lsuw)
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
> set.seed(123)
> data(us_fiscal_lsuw)
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
> set.seed(45869)
> data(us_fiscal_lsuw)
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
> set.seed(856942)
> data(us_fiscal_lsuw)
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
> set.seed(1)
> data(us_fiscal_lsuw)
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
> set.seed(5698)
> data(us_fiscal_lsuw)
> specification  = specify_bsvar_sv$new(us_fiscal_lsuw, p = 2, B = B)
> burn_in        = estimate(specification, 3, thin = 2)
**************************************************|
bsvars: Bayesian Structural Vector Autoregressions|
**************************************************|
 Gibbs sampler for the SVAR-SV model              |
   Non-centred SV model is estimated             |
**************************************************|
 Progress of the MCMC simulation for 3 draws
    Every 2th draw is saved via MCMC thinning
 Press Esc to interrupt the computations
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in estimate.BSVARSV(specification, 3, thin = 2) : 
  chol(): decomposition failed
```

**Comment by donotdespair** [comment]
Hey @mfaragd 

I think I know what that is! For the moment, would you please make the number of draws to be sampled, `S`, a positive integer multiplication of the `thin` parameter? In my function, I don't check this dependence, and it creates problems with **cpp** code. For instance, set `S=4` and `thin=2` for the trial run and something like `S=100000` and `thin=10` for the estimation or burn in. 

I will update the package with this check very soon! And then will close the issue if my suggested solution occurs one indeed.

It took me a bit to figure out the problem, as the code where a Cholesky decomposition might fail is all OK, but there's no check for these arguments that results in a misleading message.

Greetings, Tomasz

**Comment by donotdespair** [comment]
Hey @mfaragd 

The problem identified in this conversation is now handled in a new issue #33 

Thank you for your feedback that allowed its identification!

Greetings, T

**Comment by mfaragd** [comment]
Dear Prof. Tomasz,


Thank you very much for getting back to me. I have two further questions:

   1. If the time series I am analyzing includes periods with explosive
   behavior, would the bsvar_sv with the recursive identification structure be
   correct to analyze this series?
   2. Is there a direct link to the updated version of the package?

Thanks a lot for your replies


Kind regards,

Markos

**Comment by donotdespair** [comment]
Hi Markos,

:) One by one:

2. Here you go. Just install the package using code:
'''
devtools::install_git("https://github.com/donotdespair/bsvars.git")
'''
Turn off RStudio and open it again.

1. The priors can be easily set for random walk series. But if there is strong evidence in the data for explosive behaviour, then the posterior estimates of autoregressive parameters will capture that. If you're thinking of periodically explosive behaviour in line with speculative bubbles, the estimates over the whole sample will probably not capture this. The solution would be to estimate the models is subsamples. Bayesian models seem just perfect for this!
