### ISSUE TITLE
Identification with bvarsv

### ISSUE THREAD

**Issue by mfaragd** [donotdespair/bsvars#29]
Dear @donotdespair 

I am estimating an SVAR model for the oil market. Therefore, my identification has to rely on economic theory. However, since the oil price and some market indicators were highly volatile over the last four years, I have to estimate a VAR model with stochastic volatility in the innovation process (i.e., in the spirit of Cogley and Sargent (2005) and Primiceri (2005)).

In this context, I have a question about **the SVAR with Stochastic Volatility (SV) heteroskedasticity proposed by Lütkepohl,
Shang, Uzeda, and Wo´zniak (2022)** that is estimated by the "bsvars" package:

Would the estimation of this model mean that the shocks will be identified only by heteroscedasticity and not by economic theory? In other words, would you please clarify the difference between the identification estimated by this model and that estimated by Primiceri (2005)?

Looking forward to your clarification.

**Comment by donotdespair** [comment]
Hi @mfaragd 

I understand where the question is coming from, as the current version of the package does not include sufficient documentation in the form of a vignette. Also, the paper you mentioned is not yet out and only functions as a non-published manuscript. I and we are working on both outputs. The working paper should surface within a few months, and the vignette will be made available with one of the nearest package releases.

In the meantime, let me add that version 1.0.0 and the developer's version 1.0.1.9000 of the package allows the identification via exclusion restrictions, heteroskedasticity and non-normality. Exclusion restrictions can be combined with heteroskedasticity or non-normality. If you decide to impose exclusion restrictions on one, several, or all of the rows of the structural matrix, then you are identifying the corresponding shocks also via these restrictions. They should be motivated by economic theory. So, the application of exclusion restrictions facilitates theory-based identification.

If you choose not to impose them, you might still hope for the statistical identification of the shocks via volatility or non-normality. It's more difficult to give the shocks economic interpretations, but often it is feasible in well-setup systems. For instance, my experience is that the monetary policy shock for the US is easily identified via heteroskedasticity as the shock to the interest rate equation.

Finally, my models do not exhibit time variation in the structural matrix as they do in Primiceri (2005) paper that you mention.  Still, you could use their data and identifying patterns of exclusion restriction in **bsvars** package models.

Please, let me know if this helps.
