### ISSUE TITLE
Using bvarsv with a highly volatile dataset

### ISSUE THREAD

**Issue by mfaragd** [donotdespair/bsvars#30]
Hello Prof. Tomasz Woźniak,

Is it possible to use the BSVARS to analyze a dataset that is highly volatility and heteroscedastic? For example, the dollar exchange rate and oil price during the year 2022, there were many outliers and volatility during that period. We have a dataset with daily frequency. However, we need to follow the recursive identification structure to estimate our model and impose some exclusion restrictions.

Could you please comment on whether we can use the bsvars package with this dataset?

Thanks so much.

**Comment by donotdespair** [comment]
Hey @mfaragd 

I see you're interested in applying the methods to high-frequency financial data. That's really cool and what the model should be good for! So, point by point!

With exchange rates the model would work great as they are usually analysed without applying transformations (no logs, no diff). But then they are unit-root non-stationary. The benefit of using Bayesian methods is that the inference for such data is just the same as for stationary data. So as long as you include enough lags in the model (but for exchange rates one can be enough) the shocks will be stationary about `0` and the model can be used!

Also, the default option in setting the prior is the Minnesota prior for unit-root non-stationary variables. So, that's easy!

The lower triangularity of the structural matrix is also the default model specification. One can alter this, though.

Finally, the `bsvar_sv` or `bsvar_msh` models are heteroskedastic and they fit the financial data very well! Especially the former!

Please, let me know if you require some further assistance! Aha, and for the moment, I strongly recommend installing the developer's version of the package from GitHub. It makes the user's life much easier. More updates in the package and on CRAN are coming this year.

Greetings, Tomasz

**Comment by markosfarage** [comment]
Thanks @donotdespair 

I have two further questions:

1) if the time series I am analyzing includes periods with explosive behavior, would the bsvar_sv with the recursive identification structure be correct to analyze this series?
2) It's great to know that you have updated the package. Is there a direct link to the updated version?  
 
Thanks a lot for your replies
