### ISSUE TITLE
Conditional Forecasts & IRFs?

### ISSUE THREAD

**Issue by RightHandOfDoom** [donotdespair/bsvars#31]
Hello! 
Big fan of this package. Q: do you agree it would be a good idea to build a function for conditional forecasts and impulse responses (analogous to the similar functionality of the BVAR package)?
Thank you very much!

**Comment by donotdespair** [comment]
Hi @RightHandOfDoom 

Thanks for your comment and interest in this package! Of course, I agree! And I am working on this! If you install the developer's version of this package from GitHub following the instructions from [README](https://github.com/donotdespair/bsvars) file of the repo, then you will have many, many improvements already implemented! I will work within a month or two to push these changes (and several more) to CRAN. 

I know the **BVAR** package, and I appreciate their simple, user-friendly workflows. I am aiming to go in that direction with **bsvars** as well. It takes time, but sometime early next year, the package should move a lot in that direction. 

Please stay in touch with the updates and suggest more.

Greetings, Tomasz

**Comment by RightHandOfDoom** [comment]
Hello! Thank you very much for you response! Please don't feel pressured or anything. I had a look at the source code for some of the functions in your package - it is a lot of work!
Maybe some general feedback:
Overall, I feel your bsvars and bvar have a good chance to become the workhorse packages for Bayesian Macroeconometrics in R, similar to the MATLAB BVAR Toolbox. Before that, I have used (1) bvars & (2) bvarsv but (1) seems to be semi-defunct & gruggs like me need good documentation (ChatGPT helps w/that though!). The computational burden in (2) is immense and models with more than 4, 5 variables are not practical. It also offers "only" IRFs & predictive densities.
Industry practitioner like me often don't have the right to develop our own routines at work, so we are required to use available packages from CRAN (which also is a hassle sometimes but there are workarounds) that offer the functionality we need.
In my humble opinion, from a practitioner POV, the following would be the "perfect" R package for Bayesian Macroeconometrics:
 - Hierarchical Modeling of Prior Hyperparameters
 - Availability to enable stochastic volatility & TVPs
 - (General) Impulse Response Functionality, FEVD, HD
 - Structural Analysis (Zero & Sign Restrictions & their combo, IV identification, etc). There are certainly new practices in structural analysis that I am not aware of.
 - Conditional Forecasting & Scenario Analysis
 - Convergence Diagnostics 
 - Ability to estimate "large" BVARs & BVARs w/factors, w/the same functionalities (which is a hassle in itself)

Please don't consider this a "wishlist" or a list of commands (since the internet is full of impolite people who expect others to work for them for free and the bitch it does not quite suite their desires). 
Users are already very happy with what bsvars offers. And you are developing alone! I would love to help out but my programming skills in R are very average and even non-existent in Rcpp :(

**Comment by donotdespair** [comment]
Hey,

This is great! Thank you so much for this feedback and for stating your point of view! That's very useful to me! Let me wrap up what the package does, what's in the pipeline, and what would require more work...
- hierarchical modelling is extensively implemented in **bsvars** - it's a lot of flexibility with the hands-off approach for users
- prior hyperparameters - can be controlled, but... (i) has to be made more user friendly, (ii) loses on importance once hierarchical modelling is implemented as mentioned above
- SV and Markov-switching heteroskedasticity are already implemented in **bsvars**
- TVP - well, I am already working on another package [**bsvarTVPs**](https://github.com/donotdespair/bsvarTVPs) that would include this functionality to some extent - the code is working beautifully. We're working on a paper based on this, and the package needs to be more user-friendly (the developer's version includes only very lapidary help files, e.g.)
- IRFs, FEVD, HD, and more is implemented in the developer's version of the package, and I will post it on CRAN before the end of the year (sorry about the timing - I really need to prioritise my research outcomes)
- **bsvars** implement identification via exclusion restrictions and identification via heteroskedasticity. They can be very useful. Including sign restrictions would require quite different algorithms. Maybe I'll get into this in the future. But no promises, ATM.
- conditional forecasting is absent ATM - but I am thinking of a separate package for this
- convergence diagnostics - this can be done quite easily in my package - I will develop a routine that would provide the convergence results
- Large Bayesian VARs... it's a big topic depending on how many variables. My package easily deals with up to 20 - although computational times for heteroskedastic models can be substantial. If you're thinking of a hundred variables, then different model setup and algorithms would have to be implemented.

BTW. I am only authoring **bsvars** package, not **BVAR**.

And I am entirely aware of the industry requirements for such a package! I am slowly slowly getting there with this one. But also the world of Bayesian modelling is very idiosyncratic and everybody has their own model requiring different algorithms and approaches in technical terms. And the development of these things is very time-consuming! 

Thanks again for your feedback! It gives me a very strong motivation to keep up the efforts!

Greetings, T

**Comment by donotdespair** [comment]
One of the points is an issue now #32

**Comment by RightHandOfDoom** [comment]
Hi! Thank you for the comments. I am sure once the package is finished, it will become the standard (similar to vars / svars for frequentist VARs). Will check out the bsvarTVPs and the new functionalities in the developer version of bsvars.
If I find time, maybe I'll try (with ChatGPT's help!) to write a function for cond. forecasts and send them to you, if you don't mind. Maybe it satisfies your needs, but I sadly cannot make any promises.

**Comment by donotdespair** [comment]
No worries @RightHandOfDoom 

For the conditional forecasts, I already know what methods to implement. They are based on the material that is being presented at academic conferences but is not yet published. Were you thinking of the conditional forecasts a la [Zha & Waggoner (1999)](https://direct.mit.edu/rest/article/81/4/639/57170). It's a good beginning, but I am going to implement something more general, but also including this one! :)

Greetings, T
